### ISSUE TITLE
I played it, this is very epic.

### ISSUE THREAD

**Issue by KendallDoesCoding** [nairvarun/tictactoe-ai#4]
Yo,

This is so epic!

**Comment by nairvarun** [comment]
eyyy tyty. 

i've been meaning to implement a simpler version of this in javascript and maybe have it up as a static website but i'm not relly sure where to begin. you got any suggestions?

**Comment by KendallDoesCoding** [comment]
Well, I made one in JS, but you need 2 players to be playing at once, you can check it out.
http://kendalldoescoding.gq/tictactoe

**Comment by nairvarun** [comment]
interesting. i'll do that. ty

also, i'm closing this issue.

**Comment by KendallDoesCoding** [comment]
> interesting. i'll do that. ty
> 
> also, i'm closing this issue.

Cool, Idk how but if you change the code, it's possible to make a ai bot in place of the O player.

**Comment by KendallDoesCoding** [comment]
@nairvarun Refer to #5 , I added something you would like, I found the code online, but you use the same concepts if you wanna make your own code too!. You can also  add a lot more, like a level system, linked with firebase so other people can see the highscores too, etc.
